unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=-1
set smarttab

set number
set relativenumber

set hidden

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

highlight LineNr ctermfg=grey
